version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv 0.6.12
      - asdf global uv 0.6.12
    create_environment:
      - uv venv
    install:
      - uv sync --group=docs
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py
