[tox]
envlist =
    addonscript-py314
    balrogscript-py314
    beetmoverscript-py314
    bitrisescript-py314
    bouncerscript-py314
    configloader-py314
    iscript-py311
    githubscript-py314
    init-py314
    landoscript-py314
    pushapkscript-py314
    pushflatpakscript-py314
    pushmsixscript-py314
    scriptworker_client-py314
    shipitscript-py314
    signingscript-py314
    treescript-py314
    ruff

skipsdist = true

[testenv]
runner = uv-venv-lock-runner

[testenv:configloader-py311]
changedir = {toxinidir}/configloader
commands =
    tox -e py311

[testenv:init-py311]
commands =
    pytest -n auto tests

[testenv:iscript-py311]
changedir = {toxinidir}/iscript
commands =
    tox -e py311

[testenv:scriptworker_client-py311]
changedir = {toxinidir}/scriptworker_client
commands =
    tox -e py311,mypy

[testenv:addonscript-py314]
changedir = {toxinidir}/addonscript
commands =
    tox -e py314

[testenv:balrogscript-py314]
changedir = {toxinidir}/balrogscript
commands =
    tox -e py314

[testenv:beetmoverscript-py314]
changedir = {toxinidir}/beetmoverscript
commands =
    tox -e py314

[testenv:bitrisescript-py314]
changedir = {toxinidir}/bitrisescript
commands =
    tox -e py314

[testenv:bouncerscript-py314]
changedir = {toxinidir}/bouncerscript
commands =
    tox -e py314

[testenv:configloader-py314]
changedir = {toxinidir}/configloader
commands =
    tox -e py314

[testenv:init-py314]
commands =
    pytest -n auto tests

[testenv:iscript-py314]
changedir = {toxinidir}/iscript
commands =
    tox -e py314

[testenv:githubscript-py314]
changedir = {toxinidir}/githubscript
commands =
    tox -e py314

[testenv:landoscript-py314]
changedir = {toxinidir}/landoscript
commands =
    tox -e py314

[testenv:pushapkscript-py314]
changedir = {toxinidir}/pushapkscript
commands =
    tox -e py314

[testenv:pushflatpakscript-py314]
changedir = {toxinidir}/pushflatpakscript
commands =
    tox -e py314

[testenv:pushmsixscript-py314]
changedir = {toxinidir}/pushmsixscript
commands =
    tox -e py314

[testenv:scriptworker_client-py314]
changedir = {toxinidir}/scriptworker_client
commands =
    tox -e py314,mypy

[testenv:shipitscript-py314]
changedir = {toxinidir}/shipitscript
commands =
    tox -e py314

[testenv:signingscript-py314]
changedir = {toxinidir}/signingscript
commands =
    tox -e py314

[testenv:treescript-py314]
changedir = {toxinidir}/treescript
commands =
    tox -e py314

[testenv:ruff]
commands =
    ruff --version
    ruff check --verbose {toxinidir}

[testenv:ruff-format]
commands =
    ruff --version
    ruff format --diff --verbose {toxinidir}

[testenv:yamllint]
commands =
    yamllint --version
    yamllint --strict -c {toxinidir}/.yamllint {toxinidir}
