ALIASES_REGEXES = {
    "thunderbird-beta-latest": "^Thunderbird-\d+\.0b\d+$",
    "thunderbird-latest": "^Thunderbird-\d+\.\d+(\.\d+)?$",
    "fennec-beta-latest": "^Fennec-\d+\.0b\d+$",
    "fennec-latest": "^Fennec-\d+\.\d+(\.\d+)?$",
    "firefox-devedition-stub": "^Devedition-\d+\.0b\d+-stub$",
    "firefox-devedition-latest": "^Devedition-\d+\.0b\d+$",
    "firefox-devedition-latest-ssl": "^Devedition-\d+\.0b\d+-SSL$",
    "firefox-beta-stub": "^Firefox-\d+\.0b\d+-stub$",
    "firefox-beta-latest": "^Firefox-\d+\.0b\d+$",
    "firefox-beta-latest-ssl": "^Firefox-\d+\.0b\d+-SSL$",
    "firefox-stub": "^Firefox-\d+\.\d+(\.\d+)?-stub$",
    "firefox-latest": "^Firefox-\d+\.\d+(\.\d+)?$",
    "firefox-latest-ssl": "^Firefox-\d+\.\d+(\.\d+)?-SSL$",
    "firefox-esr-latest": "^Firefox-\d+\.\d+(\.\d+)?esr$",
    "firefox-esr-latest-ssl": "^Firefox-\d+\.\d+(\.\d+)?esr-SSL$",
    "firefox-esr-next-latest": "^Firefox-\d+\.\d+(\.\d+)?esr$",
    "firefox-esr-next-latest-ssl": "^Firefox-\d+\.\d+(\.\d+)?esr-SSL$",
    "firefox-sha1": "^Firefox-\d+\.\d+(\.\d+)?esr-sha1$",
    "firefox-sha1-ssl": "^Firefox-\d+\.\d+(\.\d+)?esr-sha1$"
}
