[project]
name = "pytest-scriptworker-client"
version = "0.1.0"
description = "scriptworker_client test fixtures"
authors = [
    { name = "Ben Hearsum", email = "ben@mozilla.com" }
]
dependencies = ["pytest"]

[project.entry-points.pytest11]
pytest-scriptworker-client = "pytest_scriptworker_client"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
