[project]
name = "pytest-scriptworker-client"
version = "0.1.0"
description = "scriptworker_client test fixtures"
authors = [
    { name = "Ben Hearsum", email = "ben@mozilla.com" }
]
requires-python = ">=3.8"
dependencies = ["pytest"]

[project.entry-points.pytest11]
pytest-scriptworker-client = "pytest_scriptworker_client"
