ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}

WORKDIR /app

COPY docker.d/image_setup.sh /app/

RUN /app/image_setup.sh

COPY MANIFEST.in setup.py tox.ini /app/
COPY requirements/ /app/requirements/

RUN pip install -r requirements/local.txt

COPY src/ /app/src/

ENTRYPOINT ["/usr/local/bin/tox", "-e"]
