#!/bin/bash
# This script is used by Kubernetes to ensure the health of the replica
# Non zero exit code assumes that the replica is unhealthy.

# check the last modification time of the log file
LOG_MAX_AGE_SEC=180
modified=$(date -r /app/logs/worker.log +%s)
now=$(date +%s)
age=$[ $now - $modified ]

if [ $age -gt $LOG_MAX_AGE_SEC ]; then
    echo "/app/logs/worker.log is too old: $modified"
    exit 1
fi
